### ISSUE TITLE
[Bare - task] todo 삭제하기

### ISSUE THREAD

**Issue by jjangyeunii** [jjangyeunii/pre-project-testing-app#3]
### 만들고자 하는 기능
Todo 삭제하기(Delete)

### 해당 기능을 구현하기 위해 할 일
1. [ ] todo 삭제 버튼 구현하기
2. [ ] todolist의 id와 삭제할 todo의 id를 비교하기 
3. [ ] 비교 후 같은 값을 가진 경우 삭제하기
4. [ ] 삭제한 list를 업데이트하기

### 예상 작업 시간
1h
